"""
Radio Monitor Version Information

This file is automatically generated during the build process.
DO NOT EDIT MANUALLY - it will be overwritten.

The version here represents the actual running version of the application,
not necessarily the latest version in git.
"""

__version__ = "1.1.3"
__build_date__ = "2026-02-22"
__github_url__ = "https://github.com/allurjj/radio-monitor"
